# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# æ·»åŠ æ–°èœå•é¡¹éµå¾ªä»¥ä¸‹è§„åˆ™
# menu:
#  link:               fontawesomeå›¾æ ‡ï¼Œçœç•¥å‰ç¼€ï¼Œæœ¬ä¸»é¢˜å‰ç¼€ä¸º icon-ï¼Œå¿…é¡»
#    text: About       èœå•æ˜¾ç¤ºçš„æ–‡å­—ï¼Œå¦‚æœçœç•¥å³é»˜è®¤ä¸å›¾æ ‡ä¸€è‡´ï¼Œé¦–å­—æ¯ä¼šè½¬å¤§å†™
#    url: /about       é“¾æ¥ï¼Œç»å¯¹æˆ–ç›¸å¯¹è·¯å¾„ï¼Œå¿…é¡»ã€‚
#    target: _blank    æ˜¯å¦è·³å‡ºï¼Œçœç•¥åˆ™åœ¨å½“å‰é¡µé¢æ‰“å¼€
menu:
  home:
    text: ä¸»é¡µ
    url: /
  archives:
    text: å½’æ¡£
    url: /archives
  tags:
    text: æ ‡ç­¾
    url: /tags
  th-list:
    text: åˆ†ç±»
    url: /categories
#  envelope:
#    text: E-Mail
#    url: mailto:fuzy450@foxmail.com
#    target: _blank
  qq:
    text: QQ
    url: http://wpa.qq.com/msgrd?v=3&uin=450805067&site=qq&menu=yes
    target: _blank
  link:
    text: çŸ¥ä¹
    url: http://www.zhihu.com/people/fu-zhong-yi-28
    target: _blank
  github:
    url: https://github.com/fuzhongyi
    target: _blank
#  weibo:
#    url: http://www.weibo.com/ysweb
#    target: _blank
#  link:
#    text: æµ‹è¯•
#    url: /custom

# ä½ çš„å¤´åƒurl
avatar: https://avatars2.githubusercontent.com/u/26210263?v=4&s=460
# avatar link
avatar_link: /
# å¤´åƒèƒŒæ™¯å›¾
brand: /img/brand.jpg
# favicon
favicon: /favicon.ico

# email
email: fuzy450@foxmail.com

# è®¾ç½® Android L Chrome æµè§ˆå™¨çŠ¶æ€æ é¢œè‰²
color: '#3F51B5'

# é¡µé¢æ ‡é¢˜
tags_title: æ ‡ç­¾
archives_title: å½’æ¡£
categories_title: åˆ†ç±»

# æ–‡ç« æˆªæ–­
excerpt_render: false
excerpt_length: 200
excerpt_link: é˜…è¯»å…¨æ–‡...
mathjax: false
archive_yearly: true

# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æœ€åæ›´æ–°æ—¶é—´
show_last_updated: true

# æ˜¯å¦å¼€å¯åˆ†äº«
share: true

# æ˜¯å¦å¼€å¯æ‰“èµï¼Œå…³é—­ reward: false
reward: false
#  title: è¯·æˆ‘åƒè¾£æ¡ğŸ˜~
#  wechat: http://chuantu.biz/t6/34/1504510809x2101812455.png     #å¾®ä¿¡ï¼Œå…³é—­è®¾ä¸º false
#  alipay: http://chuantu.biz/t6/34/1504511182x2101812455.png     #æ”¯ä»˜å®ï¼Œå…³é—­è®¾ä¸º false

# æ˜¯å¦å¼€å¯æœç´¢
search: true

# æ˜¯å¦å¤§å±å¹•ä¸‹æ–‡ç« é¡µéšè—å¯¼èˆª
hideMenu: true

# æ˜¯å¦å¼€å¯toc
# toc: false
toc:
  list_number: true  # æ˜¯å¦æ˜¾ç¤ºæ•°å­—æ’åº

# æ–‡ç« é¡µç•™è¨€å†…å®¹ï¼Œhexoä¸­æ‰€æœ‰å˜é‡åŠè¾…åŠ©å‡½æ•°ç­‰å‡å¯è°ƒç”¨ï¼Œå…·ä½“è¯·æŸ¥é˜… hexo.io
postMessage: <a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# ç«™é•¿ç»Ÿè®¡ï¼Œå¦‚è¦å¼€å¯ï¼Œè¾“å…¥CNZZç«™ç‚¹idï¼Œå¦‚ cnzz: 1255152447
cnzz: 1268099462

# ç™¾åº¦ç»Ÿè®¡ï¼Œå¦‚è¦å¼€å¯ï¼Œæ”¹ä¸ºä½ çš„ key
baidu_tongji: 9a62cc3b4f5c6e84c6071660c5aa8c09

# è…¾è®¯åˆ†æï¼Œå¦‚è¦å¼€å¯ï¼Œè¾“å…¥ç«™ç‚¹id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# ä»¥ä¸‹è¯„è®ºæ’ä»¶å¼€å¯ä¸€ä¸ªå³å¯
# æ˜¯å¦å¼€å¯ disqus
disqus_shortname: false
# æ˜¯å¦å¼€å¯å‹è¨€è¯„è®º, å¡«å†™å‹è¨€ç”¨æˆ·id
uyan_uid: false
# æ˜¯å¦å¼€å¯æ¥å¿…åŠ›è¯„è®º, å¡«å†™æ¥å¿…åŠ›ç”¨æˆ·uid
livere_uid: MTAyMC8zMDY2MC83MjE1
# æ˜¯å¦ä½¿ç”¨ gitmentï¼Œhttps://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# è§„èŒƒç½‘å€
# è®©æœç´¢å¼•æ“é‡å®šå‘ä½ çš„ä¸åŒåŸŸåã€ä¸åŒå­åŸŸã€åŒåŸŸä¸åŒç›®å½•çš„ç«™ç‚¹åˆ°ä½ æœŸæœ›çš„è·¯å¾„
# https://support.google.com/webmasters/answer/139066
# å‡è®¾é…ç½®ä¸º canonical: http://imys.netï¼Œé‚£ä¹ˆä»æœç´¢å¼•æ“ä¸­ www.imys.net è¿›å…¥ä¼šé‡å®šå‘åˆ° imys.net
canonical: https://xyue.me

# ç‰ˆæƒèµ·å§‹å¹´ä»½
since_year: 2017

# ç”¨æˆ·é¡µé¢ä¸­ä½œè€…ç›¸å…³çš„æè¿°æ€§æ–‡å­—ï¼Œå¦‚ä¸éœ€è¦è®¾ä¸º false
about: false

# â€œä¸è’œå­â€è®¿é—®é‡ç»Ÿè®¡ï¼Œè¯¦è§ http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: <i class="icon icon-user"></i>
  site_pv: <i class="icon icon-eye"></i>

# åŠ¨æ€å®šä¹‰title
title_change:
  normal: å’¦!å›æ¥å•¦ğŸ˜‹!
  leave: 	æ­»é¬¼å»å“ªé‡Œäº†ğŸ˜¥!

# è®¾ç½®ä¸º true å‘å¸ƒåå°†ä½¿ç”¨ unpkg cdn
cdn: true

# è®¾ç½®ä¸º true å°†ä½¿ç”¨ lightbox render å›¾ç‰‡
lightbox: true

# icpå¤‡æ¡ˆå·  ICP_license: äº¬ICPå¤‡1234556å·-1
ICP_license: false
